version: '3'
services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always

  react:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always