# docker-compose.yml

version: '3.8'
services:
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      ACME_AGREE: 'true'
      ACME_EMAIL: 'keisokoo@gmail.com'
      
volumes:
  caddy_data:
  caddy_config:
