# docker-compose.yml

version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
