# docker-compose.yml

version: '3.8'
services:
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
