# docker-compose.yml

version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules

  caddy:
    image: caddy:2.0.0
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/usr/share/caddy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
